from pathlib import Path
from dwforsec.reports.base_report import BaseReport
from dwforsec.utils.file_helpers import write_file_async

class TxtReport(BaseReport):
    async def generate(self) -> Path:
        filename = self.get_filename("txt")
        out_path = self.output_dir / "txt" / filename
        out_path.parent.mkdir(parents=True, exist_ok=True)
        
        lines = []
        lines.append("==================================================")
        lines.append("           DWForSec-ReconSuite REPORT")
        lines.append("==================================================")
        lines.append(f"Target:       {self.target}")
        lines.append(f"Scan ID:      {self.scan_id}")
        lines.append(f"Scan Time:    {self.timestamp}")
        lines.append("==================================================")
        lines.append("")
        
        # Summary
        summary = self.data.get("summary", {})
        lines.append("--- EXECUTIVE SUMMARY ---")
        lines.append(f"Total Subdomains:  {summary.get('total_subdomains', 0)}")
        lines.append(f"Live Hosts:        {summary.get('live_hosts', 0)}")
        lines.append(f"Open Ports Found:  {summary.get('open_ports', 0)}")
        lines.append(f"Technologies:      {', '.join(summary.get('technologies', []))}")
        lines.append("")
        lines.append("Findings Severity Counts:")
        lines.append(f"  Critical: {summary.get('critical', 0)}")
        lines.append(f"  High:     {summary.get('high', 0)}")
        lines.append(f"  Medium:   {summary.get('medium', 0)}")
        lines.append(f"  Low:      {summary.get('low', 0)}")
        lines.append(f"  Info:     {summary.get('info', 0)}")
        lines.append("")
        
        # Subdomains
        lines.append("--- DISCOVERED SUBDOMAINS ---")
        for sub in self.data.get("subdomains", []):
            lines.append(f"- {sub.get('subdomain')} (IP: {sub.get('ip_address') or 'N/A'}, Status: {sub.get('status_code') or 'N/A'}, Title: {sub.get('title') or 'N/A'})")
        lines.append("")
        
        # Findings
        lines.append("--- VULNERABILITY FINDINGS ---")
        for f in self.data.get("findings", []):
            lines.append(f"[{f.get('severity', 'info').upper()}] {f.get('template_id') or f.get('tool')}")
            lines.append(f"  Matched: {f.get('matched_url') or f.get('host')}")
            if f.get('description'):
                lines.append(f"  Desc:    {f.get('description')}")
            if f.get('recommendation'):
                lines.append(f"  Remedy:  {f.get('recommendation')}")
            lines.append("")
            
        # SSL Findings
        lines.append("--- SSL/TLS FINDINGS ---")
        for s in self.data.get("ssl_findings", []):
            lines.append(f"Host: {s.get('host')}")
            lines.append(f"  TLS:     {s.get('tls_version') or 'N/A'}")
            lines.append(f"  Issuer:  {s.get('issuer') or 'N/A'}")
            lines.append(f"  Expiry:  {s.get('expiry_date') or 'N/A'}")
            if s.get('weak_ciphers'):
                lines.append(f"  Weak Ciphers: {s.get('weak_ciphers')}")
            if s.get('recommendation'):
                lines.append(f"  Remedy:  {s.get('recommendation')}")
            lines.append("")
            
        # JS exposure
        lines.append("--- JAVASCRIPT EXPOSURE ANALYSIS ---")
        for j in self.data.get("js_analysis", []):
            lines.append(f"File: {j.get('url')}")
            if j.get("secrets_found"):
                lines.append(f"  Secrets: {j.get('secrets_found')}")
            lines.append("")
            
        # Footer
        lines.append("==================================================")
        lines.append("Report generated by DWForSec-ReconSuite.")
        
        content = "\n".join(lines)
        await write_file_async(out_path, content)
        return out_path
